### ISSUE TITLE
Week 8 Crossover Grading - Natasha

### ISSUE THREAD

**Issue by mistylavender** [ridhimainukurti/p1-Valid#43]
[FRQ Wiki](https://github.com/ridhimainukurti/p1-Valid/wiki/Natasha-FRQ-Wiki)
[Repl Repository](https://replit.com/@MistyLavender/Natasha-FRQs#Main.java)

Grading Completed in Comments

**Comment by wrachel** [comment]
Natasha's Score(s)
Graded by Rachel

| Requirement | Evaluation | 
| -------------- | ------------ | 
|  Each individual has GitHub Page, Wiki, or deployed Web Page that Highlights talking points and learnings from each FRQ                     | Natasha has a Github Wiki page that highlights key ideas/things covered for each FRQ. Reflection is also just a bullet-pointed list, could show more thorough learnings. | 
Each Individual has their own set of FRQs running under one page or menu (ie Deployed Java/Spring or Replit) | Individual has all her FRQs running on one Replit page that was linked to me. FRQs are easy to find. The only thing is that FRQ8 does not seem to be working from the users end (no error messages either), so that is a little confusing. It would be nice if even if it didn't take user input, it would print out the solutions to the FRQ (like you did with FRQ9) |
 Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit | Yes, all source code is linked on the review ticket and can be found on Replit. |
At least 2 FRQs with input and output (10%) | Most of the FRQs (except for 8,9) allow for user input. Very nice job with that! | 

Overall comments: 
Every FRQ was very easy to find and in one place. It was also very easy to find the source code, and all reflections/source code are linked to one review ticket (very organized!). I see some faults in that a lot of the FRQs don't have any explanation behind them/don't guide the user very well. Only if you have done every FRQ in the same way that we are required to does it make sense. I'm also not sure if it is linked on her website/webpage or is associated with her project. Still, everything was very organized and interactive. 

Scoring:
9.4/10. Most FRQs were completed and somehow implemented as well as easy to find. Reflections could have been a little more thorough (more insight rather than bullet pointed list) so -0.1, and FRQ8 was confusing so -0.5, but otherwise well done!
